apiVersion: v1  # API 버전
kind: Service   # 리소스 종류 (Service)
metadata:
  name: mydb  # 서비스 이름
spec:
  selector:
    app: mydb  # mydb 라벨을 가진 Pod에 트래픽 전달
  ports:
    - protocol: TCP   # 네트워크 프로토콜 (TCP) 기본값이라 생략 가능
      port: 5432      # 다른 Pod가 접근할 서비스 포트
      targetPort: 5432  # 실제 PostgreSQL 컨테이너의 포트
      nodePort: 30007
  type: NodePort  # 로컬 컴퓨터에서 접근하기 위함
