apiVersion: apps/v1  # 쿠버네티스 앱 배포 API 버전
kind: Deployment     # 리소스 종류 (Deployment)
metadata:
  name: blog-deployment  # Deployment의 이름
spec:
  replicas: 2  # Pod를 몇 개 실행할 것인지 (수평 확장)
  selector:
    matchLabels:
      app: blog  # 이 라벨을 가진 Pod를 관리
  template:
    metadata:
      labels:
        app: blog  # Pod에 설정된 라벨
    spec:
      containers:
        - name: blog  # 컨테이너의 이름
          image: blog-image:latest  # 도커 이미지 태그 추가
          imagePullPolicy: Never  # Minikube가 로컬 이미지를 사용하도록 설정
          ports:
            - containerPort: 8080  # 컨테이너 내부에서 노출할 포트
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://mydb:5432/blog"
            - name: SPRING_DATASOURCE_USERNAME
              value: "manager"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "manager0"
