apiVersion: v1  # API 버전
kind: Service   # 리소스 종류 (Service)
metadata:
  name: blog-service  # 서비스 이름
spec:
  selector:
    app: blog  # myproject 라벨을 가진 Pod를 대상으로 서비스 제공
  ports:
    - protocol: TCP   # 네트워크 프로토콜 (TCP)
      port: 80        # 서비스가 노출할 포트 (외부 접근)
      targetPort: 8080  # Pod 내 애플리케이션이 사용하는 포트
  type: NodePort  # 클러스터 외부에서도 접근 가능하도록 설정
